export const seasons = ["spring", "summer", "autumn", "winter"];
export const sex = ["Unisex", "Man", "Woman", "Сhildren"];
export const size = [
  [38, 45],
  [34, 42],
  [25, 36],
];
export const category = [
  "belt",
  "backpack",
  "blouse",
  "bikini",
  "coat",
  "costume",
  "cardigan",
  "dress",
  "dinner jacket ",
  "gloves",
  "hat",
  "hoodie = hoody",
  "jacket",
  "jeans",
  "jersey",
  "jumper",
  "overcoat",
  "polo neck",
  "scarf",
  "shirt",
  "shorts",
  "skirt",
  "socks",
  "sweater",
  "swimsuit / bathing suit",
  "tie",
  "tights",
  "track suit",
  "trousers",
  "T-shirt",
  "waistcoat",
  "boots",
  "flip flops",
  "heels",
  "sandals",
  "shoes",
  "slippers",
  "trainers",
  "pajamas",
  "nightgown",
  "nightshirt",
  "bathrobe/robe",
  "undershirt/tee shirt",
  "(jockey) shorts/underpants",
  "boxer shorts",
  "long underwear/long johns",
  "panties/underpants",
  "briefs",
  "bra",
  "camisole",
  "slip",
  "half slip",
  "stockings",
  "knee socks",
  "pumps",
  "loafers",
  "sneakers",
  "tennis shoes",
  "running shoes",
  "high tops/high-top sneakers",
  "thongs/flip flops",
  "work boots",
  "hiking boots",
  "cowboy boots",
  "moccasins",
];
